apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-snapshot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: container-snapshot
  template:
    metadata:
      labels:
        name: container-snapshot
    spec:
      serviceAccountName: container-snapshot
      containers:
        - name: container-snapshot
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - container-snapshot
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "container-snapshot"
