name: Container Snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download
        go mod verify

    - name: Test
      run: go test -v ./...

  build:
    name: build docker images
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build container snapshot operator
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: houz42
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: 033751eb-565f-423c-b045-bd092e47b470
          # Docker repository to tag the image with
          repository: supremind/container-snapshot-operator
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: ./build/Dockerfile
          # Sets the target stage to build
          target: release-operator
          # Adds labels with git repository information to the built image
          add_git_labels: true
          # Whether to push the image
          push: true

      - name: Build container snapshot worker
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: houz42
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: 033751eb-565f-423c-b045-bd092e47b470
          # Docker repository to tag the image with
          repository: supremind/container-snapshot-worker
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: ./build/Dockerfile
          # Sets the target stage to build
          target: release-worker
          # Adds labels with git repository information to the built image
          add_git_labels: true
          # Whether to push the image
          push: true
