name: Container Snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-coverage:
    name: test and coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: coverage.out
          outfile: coverage.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  # see https://github.com/marketplace/actions/build-and-push-docker-images
  build:
    name: build docker images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      VERSION: v0.0.1

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build container snapshot operator
        uses: docker/build-push-action@v1.1.0
        with:
          username: houz42
          password: ${{ secrets.IMAGE_PUSH_HOUZ }}
          repository: supremind/container-snapshot-operator
          tag_with_ref: true
          dockerfile: ./build/Dockerfile
          target: release-operator
          add_git_labels: true
          push: true

      - name: Build container snapshot worker
        uses: docker/build-push-action@v1.1.0
        with:
          username: houz42
          password: ${{ secrets.IMAGE_PUSH_HOUZ }}
          repository: supremind/container-snapshot-worker
          tag_with_ref: true
          dockerfile: ./build/Dockerfile
          target: release-worker
          add_git_labels: true
          push: true
